[package]
name = "false_space"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.17.0"
winit = "0.28.6"

pollster = "0.3.0"
bytemuck = { version = "1.14.0", features = [ "derive" ] }
rand = "0.8.5"
glam = "0.24.1"
image = "0.24.7"

log = "0.4.20"
env_logger = "0.10.0"

[profile.flamegraph]
inherits = "release"
debug = true

[profile.flamegraph_no_inline]
inherits = "release"
debug = true
opt-level=0