[package]
name = "false_space"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.17.1"
winit = "0.28.7"

pollster = "0.3.0"
bytemuck = { version = "1.14.0", features = [ "derive" ] }
glam = "0.24.2"
image = "0.24.7"
hashbrown = "0.14.1"

log = "0.4.20"
env_logger = "0.10.0"

[profile.flamegraph]
inherits = "release"
debug = true

[profile.flamegraph_no_inline]
inherits = "release"
debug = true
opt-level=0