[package]
name = "false_space"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.16.2"
winit = "0.28.6"

pollster = "0.3.0"
bytemuck = { version = "1.13.1", features = [ "derive" ] }

log = "0.4.19"
env_logger = "0.10.0"